---


- name: Ensure interfaces.d exists
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: "0755"

- name: Configure leaves network interfaces
  template:
    src: interfaces-leaves.j2
    dest: /etc/network/interfaces.d/10-lab.cfg
    mode: "0644"

- name: Ensure rt_tables.d exists
  file:
    path: /etc/iproute2/rt_tables.d
    state: directory
    mode: "0755"

- name: Ensure ifupdown2 VRF map file exists
  copy:
    dest: /etc/iproute2/rt_tables.d/ifupdown2_vrf_map.conf
    content: ""
    owner: root
    group: root
    mode: "0644"
    force: no

- name: Reload all interfaces (non-disruptive)
  command: ifreload -a