---

interfaces:
  - name: "eth1"
    address: "10.1.2.1/30"
    connected_to: "spine01"
  - name: "eth2"
    address: "10.2.2.1/30"
    connected_to: "spine02"
  - name: "eth3"
    address: "10.0.20.1/30"
    connected_to: "vm02"
    vrf: vrfA
  - name: "eth4"
    address: "10.0.21.1/30"
    connected_to: "vm02"
vnix:
  - id: 10020
    rt: 20
vlans:
  - id: 10
    ip: "10.1.120.1/24"
    vrf: vrfA
  - id: 20
    vrf: vrfA
vrfs:
  - id: vrfA
    vni: 10020

lo_address: 10.0.0.2/32

router_id: 10.0.0.2

ospf_networks:
  - subnet: "10.0.0.2/32"
  - subnet: "10.1.2.0/30"
  - subnet: "10.2.2.0/30"
  - subnet: "10.0.20.0/30"
  - subnet: "10.0.21.0/30"