---

interfaces:
  - name: "eth1"
    address: "10.1.3.1/30"
    connected_to: "spine01"
  - name: "eth2"
    address: "10.2.3.1/30"
    connected_to: "spine02"
  - name: "eth3"
    address: "10.0.30.1/30"
    connected_to: "vm03"
  - name: "eth4"
    address: "10.0.31.1/30"
    connected_to: "vm03"
    vrf: vrfB
vnix:
  - id: 10040
    rt: 40
vlans:
  - id: 30
    ip: "10.1.131.1/24"
    vrf: vrfB
  - id: 40
    vrf: vrfB
vrfs:
  - id: vrfB
    vni: 10040

lo_address: 10.0.0.3/32

router_id: 10.0.0.3

ospf_networks:
  - subnet: "10.0.0.3/32"
  - subnet: "10.1.3.0/30"
  - subnet: "10.2.3.0/30"
  - subnet: "10.0.30.0/30"
  - subnet: "10.0.31.0/30"