---
- name: Configure leaves network interfaces
  template:
    src: interfaces-leaves.j2
    dest: /etc/network/interfaces
  notify: restart networking
  tags: no-vxlan

- name: Configure leaves network interfaces for vxlan
  template:
    src: interfaces-leaves-vxlan.j2
    dest: /etc/network/interfaces
  notify:
    - restart networking
    - restart frr
  tags: vxlan

- name: Configure leaves network interfaces for segregated VRF interfaces without route-maps
  template:
    src: interfaces-leaves-vrf-no-rm.j2
    dest: /etc/network/interfaces
  notify:
    - restart networking
    - restart frr
  tags: vrf-no-rm

- name: Configure leaves network interfaces for segregated VRF interfaces
  template:
    src: interfaces-leaves-vrf.j2
    dest: /etc/network/interfaces
  notify:
    - restart networking
    - restart frr
  tags: vrf

- name: Ensure networking is restarted
  meta: flush_handlers