## Config for VM only
- name: Include vms interfaces configuration tasks
  include_tasks: vms.yml
  when: inventory_hostname in groups['vms']
  tags: basic

## Config without VXLAN
## Spines don't have VXLAN config anyway, so it's fine
- name: Include spines interfaces configuration tasks
  include_tasks: spines.yml
  when: inventory_hostname in groups['spines']

- name: Include leaves interfaces configuration tasks
  include_tasks: leaves.yml
  when: inventory_hostname in groups['leaves']
  tags: no-vxlan

## Config with VXLAN for the leaves
- name: Include leaves interfaces configuration tasks
  include_tasks: leaves.yml
  when: inventory_hostname in groups['leaves']
  tags: vxlan

## Config with segregated VRF for the leaves without route-maps
- name: Include leaves interfaces configuration tasks
  include_tasks: leaves.yml
  when: inventory_hostname in groups['leaves']
  tags: vrf-no-rm
## Config for VM only with different routes for VRF without route-maps setup
- name: Include vms interfaces configuration tasks
  include_tasks: vms.yml
  when: inventory_hostname in groups['vms']
  tags: vrf-no-rm

## Config with segregated VRF for the leaves
- name: Include leaves interfaces configuration tasks
  include_tasks: leaves.yml
  when: inventory_hostname in groups['leaves']
  tags: vrf

