---
- name: Configure vm network interfaces
  template:
    src: interfaces-vms.j2
    dest: /etc/network/interfaces
  register: interfaces_rendered
  tags: basic

- name: Configure vm network interfaces
  template:
    src: interfaces-vms-vrf-no-rm.j2
    dest: /etc/network/interfaces
  register: interfaces_rendered
  tags: vrf-no-rm

# Assuming this task succeeds and the file is correctly placed

- name: Slurp the content of /etc/network/interfaces
  slurp:
    src: /etc/network/interfaces
  register: slurped_interfaces
  tags: vrf-no-rm,basic

- name: Display the content of /etc/network/interfaces
  debug:
    msg: "{{ slurped_interfaces['content'] | b64decode }}"
  tags: vrf-no-rm,basic

- name: Ensure ifupdown2 is installed
  ansible.builtin.apt:
    name: ifupdown2
    state: present
  become: yes
  tags: vrf-no-rm,basic

- name: Reconfigure network interfaces
  block:
    - name: Attempt to bring down and then up the interface
      shell: ifdown {{ item.name }} && ifup {{ item.name }}
      loop: "{{ interfaces }}"
      ignore_errors: yes
    - name: Ensure the interface is up
      shell: ifup {{ item.name }}
      loop: "{{ interfaces }}"
      ignore_errors: yes
    - name: Ensure the interface is up (it's buggy sometimes)
      shell: ifup {{ item.name }}
      loop: "{{ interfaces }}"
      ignore_errors: yes
  tags: vrf-no-rm,basic
