---

lo_address: 10.0.0.3/32

router_id: 10.0.0.3

ospf_networks:
  - subnet: "10.0.0.3/32"
  - subnet: "10.1.3.0/30"
  - subnet: "10.2.3.0/30"
  - subnet: "10.0.30.0/30"
  - subnet: "10.0.31.0/30"

### choubidou VXLAN "basic" config with 2 VRF and one leak (with --tags vxlan)
interfaces:
  - name: "swp1"
    address: "10.1.3.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.3.1/30"
    connected_to: "spine02"
  - name: "swp3"
    address: "10.0.30.1/30"
    connected_to: "vm03"
    vrf: choubidou
  - name: "swp4"
    address: "10.0.31.1/30"
    connected_to: "vm03"

vnix:
  - id: 10040
    rt: 40

vlans:
  - id: 30
    ip: "10.1.130.1/24"
    vrf: choubidou
  - id: 40
    vrf: choubidou

vrfs:
  - id: choubidou
    vni: 10040
### END of choubidou VXLAN "basic" config with 2 VRF and one leak (with --tags vxlan)



### Segmented VRF variables with multiple leaking configs without route-maps (with --tags vrf-no-rm)
vnrm_interfaces:
  - name: "swp1"
    address: "10.1.3.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.3.1/30"
    connected_to: "spine02"
  - name: "swp3"
    address: "10.0.30.1/30"
    connected_to: "vm03"
    vrf: vrfB
  - name: "swp4"
    address: "10.0.31.1/30"
    connected_to: "vm03"
    vrf: vrfD

vnrm_vnix:
  - id: 10020
    rt: 20
  - id: 10080
    rt: 80

vnrm_vlans:
  - id: 10
    ip: "10.1.130.1/24"
    vrf: vrfB
  - id: 20
    vrf: vrfB
  - id: 60
    ip: "10.1.131.1/24"
    vrf: vrfD
  - id: 80
    vrf: vrfD

vnrm_vrfs:
  - id: vrfD
    vni: 10080
    vrf_to_leak: vrfB
  - id: vrfB
    vni: 10020
    vrf_to_leak: vrfD

leaking: yes
### End of Segmented VRF variables with multiple leaking configs without route-maps (with --tags vrf-no-rm)

### Segmented VRF variables (with --tags vrf)
seg_vrfs:
  - id: vrfC
    vni: 10030

seg_vrfs_interfaces:
  - name: "swp1"
    address: "10.1.3.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.3.1/30"
    connected_to: "spine02"
  - name: "swp3"
    address: "10.0.30.1/30"
    connected_to: "vm03"
    vrf: vrfC
  - name: "swp4"
    address: "10.0.31.1/30"
    connected_to: "vm03"

seg_vrfs_vlans:
  - id: 30
    ip: "10.1.131.1/24"
    vrf: vrfC

seg_vrfs_vnix:
  - id: 10030
    rt: 30  
### End of Segmented VRF variables (with --tags vrf)