---
interfaces:
  - name: "eth1"
    address: "10.0.30.2"
    netmask: "255.255.255.252"
    connected_to: "leaf03"
    gateway: "10.0.30.1"
    routes:
    - subnet: "10.0.10.0/24"
    - subnet: "10.0.20.0/24"
    - subnet: "10.1.0.0/16"
    - subnet: "10.2.0.0/16"
    - subnet: "10.1.130.0/24"
    - subnet: "10.1.110.0/24"

### --tags vrf-no-rm #### TO MODIFY
vnrm_interfaces:
  - name: "eth1"
    address: "10.0.30.2"
    netmask: "255.255.255.252"
    connected_to: "leaf03-swp3_vrfB"
    gateway: "10.0.30.1"
  - name: "eth2"
    address: "10.0.31.2"
    netmask: "255.255.255.252"
    connected_to: "leaf03-swp4_vrfD"
    gateway: "10.0.31.1"
    routes:
    - subnet: "10.0.10.0/24"
    - subnet: "10.0.20.0/24"
    - subnet: "10.1.0.0/16"
    - subnet: "10.2.0.0/16"
    - subnet: "10.1.120.0/24"
    - subnet: "10.1.110.0/24"
    - subnet: "10.1.111.0/24"
    - subnet: "10.1.121.0/24"
    - subnet: "10.0.11.0/24"
    - subnet: "10.0.21.0/24"