---
interfaces:
  - name: "swp1"
    address: "10.1.2.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.2.1/30"
    connected_to: "spine02"
  - name: "swp3"
    address: "10.0.20.1/30"
    connected_to: "vm02"
    vrf: vrfB
  - name: "swp4"
    address: "10.0.21.1/30"
    connected_to: "vm02"
vlans:
  - id: 10
    ip: "10.1.111.1/24"
    vrf: vrfA
  - id: 20
    ip: "10.1.121.1/24"
    vrf: vrfB
vnix:
  - id: 10010
    rt: 10
  - id: 10020
    rt: 20
vrfs:
  - id: vrfB
    address: "10.0.20.1/30"
    vni: 10020
    rt: 20
    target: 
      - id: vrfA
        router_id: 10.0.0.1
        vni: 10010
        rt: 10
  - id: vrfA
    address: "10.0.10.1/30"
    vni: 10010
    rt: 10
    target: 
      - id: vrfB
        router_id: 10.0.0.2
        vni: 10020
        rt: 20

lo_address: 10.0.0.2/32

router_id: 10.0.0.2

ospf_networks:
  - subnet: "10.0.0.2/32"
  - subnet: "10.1.2.0/30"
  - subnet: "10.2.2.0/30"
  - subnet: "10.0.20.0/30"
  - subnet: "10.0.21.0/30"