---
interfaces:
  - name: "swp1"
    address: "10.1.1.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.1.1/30"
    connected_to: "spine02"
  - name: "swp3"
    address: "10.0.10.1/30"
    connected_to: "vm01"
    vrf: vrfA
  - name: "swp4"
    address: "10.0.11.1/30"
    connected_to: "vm01"
vlans:
  - id: 10
    ip: "10.1.111.1/24"
    vrf: vrfA
  - id: 20
    ip: "10.1.121.1/24"
    vrf: vrfB
  - id: 30
    ip: "10.1.131.1/24"
    vrf: vrfC
vnix:
  - id: 10010
    rt: 10
  - id: 10020
    rt: 20
  - id: 10030
    rt: 30
vrfs:
  - id: vrfA
    address: "10.0.10.1/30"
    vni: 10010
    rt: 10
    target: 
      - id: vrfB
        router_id: 10.0.0.2
        vni: 10020
        rt: 20
      - id: vrfC
        router_id: 10.0.0.3
        vni: 10030
        rt: 30
  - id: vrfB
    address: "10.0.20.1/30"
    vni: 10020
    rt: 20
    target: 
      - id: vrfA
        router_id: 10.0.0.1
        vni: 10010
        rt: 10
  - id: vrfC
    address: "10.0.30.1/30"
    vni: 10030
    rt: 30
    target: 
      - id: vrfA
        router_id: 10.0.0.1
        vni: 10010
        rt: 10

lo_address: 10.0.0.1/32

router_id: 10.0.0.1

ospf_networks:
  - subnet: "10.0.0.1/32"
  - subnet: "10.1.1.0/30"
  - subnet: "10.2.1.0/30"
  - subnet: "10.0.10.0/30"
  - subnet: "10.0.11.0/30"