---
interfaces:
  - name: "swp1"
    address: "10.1.3.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.3.1/30"
    connected_to: "spine02"
  - name: "swp3"
    address: "10.0.30.1/30"
    connected_to: "vm03"
    vrf: vrfC
  - name: "swp4"
    address: "10.0.31.1/30"
    connected_to: "vm03"
vrfs:
  - id: vrfC
    address: "10.0.30.1/30"
    vni: 10030
    rt: 30
    target: 
      - id: vrfA
        router_id: 10.0.0.1
        vni: 10010
        rt: 10
  - id: vrfA
    address: "10.0.10.1/30"
    vni: 10010
    rt: 10
    target: 
      - id: vrfC
        router_id: 10.0.0.3
        vni: 10030
        rt: 30
vlans:
  - id: 10
    ip: "10.1.111.1/24"
    vrf: vrfA
  - id: 30
    ip: "10.1.131.1/24"
    vrf: vrfC
vnix:
  - id: 10010
    rt: 10
  - id: 10030
    rt: 30

lo_address: 10.0.0.3/32

router_id: 10.0.0.3

ospf_networks:
  - subnet: "10.0.0.3/32"
  - subnet: "10.1.3.0/30"
  - subnet: "10.2.3.0/30"
  - subnet: "10.0.30.0/30"
  - subnet: "10.0.31.0/30"