---
### OSPF/BGP daemons
- name: Enable OSPF daemon
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^ospfd='
    line: 'ospfd=yes'
- name: Enable OSPF6 daemon
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^ospf6d='
    line: 'ospf6d=yes'
- name: Enable BGP daemon
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^bgpd='
    line: 'bgpd=yes'
### daemons end
