---

- name: Ensure interfaces.d exists
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: "0755"

- name: Configure VM network interfaces
  template:
    src: interfaces-vms.j2
    dest: /etc/network/interfaces.d/10-lab.cfg
    mode: "0644"

- name: Prefer Vagrant NAT on eth0 (set metric 50 under eth0 dhcp stanza)
  lineinfile:
    path: /etc/network/interfaces
    insertafter: '^iface eth0 inet dhcp$'
    regexp: '^\s*metric\s+50$'
    line: '    metric 50'
    state: present
    backup: false

## reload all interfaces
- name: ifreload
  command:
    cmd: ifreload -a

- name: Specific for Debian issue with routes
  block:
    - name: Attempt to bring down all interfaces
      shell: ifdown {{ item.name }}
      loop: "{{ interfaces }}"
      ignore_errors: yes
    - name: Ensure the interface is up
      shell: ifup {{ item.name }}
      loop: "{{ interfaces }}"
      ignore_errors: yes