---

- name: Ensure ifupdown2 is installed
  apt:
    name: ifupdown2
    state: present
  become: yes

- name: Make enp0s3 IPv6 stanza compatible with ifupdown2
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^iface\s+enp0s3\s+inet6\s+auto$'
    line: 'iface enp0s3 inet6 dhcp'

- name: Ensure /etc/sysctl.d exists
  file:
    path: /etc/sysctl.d
    state: directory
    mode: "0755"

- name: Install router sysctl config for forwarding and redirects
  copy:
    dest: /etc/sysctl.d/99-router.conf
    content: |
      # Enable IPv4/IPv6 forwarding
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1

      # Disable ICMP redirects
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.send_redirects = 0
    mode: "0644"

- name: Reload sysctl to apply immediately
  command: sysctl --system
  changed_when: false