---
### OSPF/PIM daemons
- name: Enable OSPF daemon
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^ospfd='
    line: 'ospfd=yes'
  tags: OSPF,BGP,vxlan,vrf

- name: Enable OSPF6 daemon
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^ospf6d='
    line: 'ospf6d=yes'
  tags: OSPF,BGP,vxlan,vrf

- name: Enable PIM daemon
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^pimd='
    line: 'pimd=yes'
  tags: OSPF,BGP,vxlan,vrf
### OSPFd

### OSPFd
- name: Configure FRR for OSPF and PIM
  template:
    src: frr-leaves-ospf.j2
    dest: /etc/frr/frr.conf
  notify: restart frr
  tags: OSPF
### OSPFd

### BGP daemon
- name: Enable BGP daemon
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^bgpd='
    line: 'bgpd=yes'
  tags: BGP,vxlan,vrf
### BGP daemon

### BGP
- name: Configure FRR for BGP
  template:
    src: frr-leaves-bgp.j2
    dest: /etc/frr/frr.conf
  notify: restart frr
  tags: BGP
### BGP

### vxlan
- name: Configure vxlans
  template:
    src: frr-leaves-bgp-vxlan.j2
    dest: /etc/frr/frr.conf
  notify: restart frr
  tags: vxlan
###

### segregated VRF
- name: Configure segregated VRF without route-maps
  template:
    src: frr-leaves-bgp-vrf-no-rm.j2
    dest: /etc/frr/frr.conf
  notify: restart frr
  tags: vrf-no-rm
###

### segregated VRF
- name: Configure segregated VRF
  template:
    src: frr-leaves-bgp-vrf.j2
    dest: /etc/frr/frr.conf
  notify: restart frr
  tags: vrf
###