---
- name: ifreload
  command:
    cmd: ifreload -a
  async: 10
  poll: 0
  ignore_errors: true

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 15

- name: Reload systemd and restart wait-online
  systemd:
    daemon_reload: true
    name: systemd-networkd-wait-online.service
    state: restarted
  failed_when: false